### ISSUE TITLE
specialTiles and CalculateLocation()

### ISSUE THREAD

**Issue by jsi4603** [superjeffreyc/Yut#12]
Hello

I have been using the app yut and I have a suggestion.

According to the original rules of yut, there are two possible choices when you arrive at special tiles.
I know it's designed to recommend the best location for players, but wouldn't it be fun to leave the decision to them?

**Comment by superjeffc** [comment]
Agreed. Added in commit ff5bf7fdf52b5be6e6943a302a83b8bbadda7924.

**Comment by superjeffc** [comment]
I should also mention that the Google Play app version that contains this fix is 3.1.
